### ISSUE TITLE
Bug running generate testcase

### ISSUE THREAD

**Issue by TLDart** [p4gauntlet/gauntlet#64]
# Bug running generate testcase

Good afternoon,
I was trying to run the generate_test_case executable and there seems to be a problem. Can you please clarify if the problem is on my end?

Best regards,
Duarte Dias.

```bash
tldart@ubuntu:~/gauntlet$ sudo -E bin/generate_test_case -i out.p4 -r --arch tna
INFO:Converting p4 to z3 python with command /home/tldart/gauntlet/modules/p4c/build/p4toz3 out.p4 --output /home/tldart/gauntlet/validated/out/out.py -I /home/tldart/gauntlet/tofino/bf_src/install/share/p4c/p4include/  
ERROR:BEGIN ########################################
ERROR:Failed while executing:
/home/tldart/gauntlet/modules/p4c/build/p4toz3 out.p4 --output /home/tldart/gauntlet/validated/out/out.py -I /home/tldart/gauntlet/tofino/bf_src/install/share/p4c/p4include/  (...)

ERROR:Output:
[--Werror=unknown] error: Unknown option --output
/home/tldart/gauntlet/modules/p4c/build/p4toz3: Compile a P4 program
--help                                  Print this help message
--version                               Print compiler version
-I path                                 Specify include path (passed to preprocessor)
-D arg=value                            Define macro (passed to preprocessor)
-U arg                                  Undefine macro (passed to preprocessor)
-E                                      Preprocess only, do not compile (prints program on stdout)
-M                                      Output `make` dependency rule only (passed to preprocessor)
-MD                                     Output `make` dependency rule to file as side effect (passed to preprocessor)
-MF file                                With -M, specify output file for dependencies (passed to preprocessor)
-MG                                     with -M, suppress errors for missing headers (passed to preprocessor)
-MP                                     with -M, add phony target for each dependency (passed to preprocessor)
-MT target                              With -M, override target of the output rule (passed to preprocessor)
-MQ target                              Like -Mt, override target but quote special characters (passed to preprocessor)
--std {p4-14|p4-16}                     Specify language version to compile.
--nocpp                                 Skip preprocess, assume input file is already preprocessed.
--disable-annotations[=annotations]     Specify a (comma separated) list of annotations that should be ignored by
                                        the compiler. A warning will be printed that the annotation is ignored
--Wdisable[=diagnostic]                 Disable a compiler diagnostic, or disable all warnings if no diagnostic is specified.
--Wwarn[=diagnostic]                    Report a warning for a compiler diagnostic, or treat all warnings as warnings (the default) if no diagnostic is specified.
--Werror[=diagnostic]                   Report an error for a compiler diagnostic, or treat all warnings as errors if no diagnostic is specified.
--maxErrorCount errorCount              Set the maximum number of errors to display before failing.
-T loglevel                             [Compiler debugging] Adjust logging level per file (see below)
-v                                      [Compiler debugging] Increase verbosity level (can be repeated)
--top4 pass1[,pass2]                    [Compiler debugging] Dump the P4 representation after
                                        passes whose name contains one of `passX' substrings.
                                        When '-v' is used this will include the compiler IR.
--dump folder                           [Compiler debugging] Folder where P4 programs are dumped
--parser-inline-opt                     Enable optimization of inlining of callee parsers (subparsers).
                                        The optimization is disabled by default.
                                        When the optimization is disabled, for each invocation of the subparser
                                        all states of the subparser are inlined, which means that the subparser
                                        might be inlined multiple times even if it is the same instance
                                        which is invoked multiple times.
                                        When the optimization is enabled, compiler tries to identify the cases,
                                        when it can inline the subparser's states only once for multiple
                                        invocations of the same subparser instance.
--doNotEmitIncludes condition           [Compiler debugging] If true do not generate #include statements
--excludeFrontendPasses pass1[,pass2]   Exclude passes from frontend passes whose name is equal
                                        to one of `passX' strings.
--listFrontendPasses                    List exact names of all frontend passes
--excludeMidendPasses pass1[,pass2]     Exclude passes from midend passes whose name is equal
                                        to one of `passX' strings.
--toJSON file                           Dump the compiler IR after the midend as JSON in the specified file.
--ndebug                                Compile program in non-debug mode.
--testJson                              [Compiler debugging] Dump and undump the IR
--pp file                               Pretty-print the program in the specified file.
--p4runtime-file file                   Write a P4Runtime control plane API description to the specified file.
                                        [Deprecated; use '--p4runtime-files' instead].
--p4runtime-entries-file file           Write static table entries as a P4Runtime WriteRequest messageto the specified file.
                                        [Deprecated; use '--p4runtime-entries-files' instead].
--p4runtime-files filelist              Write the P4Runtime control plane API description to the specified
                                        files (comma-separated list). The format is inferred from the file
                                        suffix: .txt, .json, .bin
--p4runtime-entries-files files         Write static table entries as a P4Runtime WriteRequest message
                                        to the specified files (comma-separated list); the file format is
                                        inferred from the suffix. Legal suffixes are .json, .txt and .bin
--p4runtime-format {binary,json,text}   Choose output format for the P4Runtime API description (default is binary).
                                        [Deprecated; use '--p4runtime-files' instead].
--target target                         Compile for the specified target device.
--arch arch                             Compile for the specified architecture.
--loopsUnroll                           Unrolling all parser's loops
Additional usage instructions:
loglevel format is: "sourceFile:level,...,sourceFile:level"
where 'sourceFile' is a compiler source file and 'level' is the verbosity level for LOG messages in that file

ERROR:END ########################################
ERROR:Failed to translate P4 to Python.
Traceback (most recent call last):
  File "/home/tldart/gauntlet/bin/../src/generate_p4_test.py", line 652, in <module>
    main(arguments)
  File "/home/tldart/gauntlet/bin/../src/generate_p4_test.py", line 594, in main
    result = perform_blackbox_test(config)
  File "/home/tldart/gauntlet/bin/../src/generate_p4_test.py", line 536, in perform_blackbox_test
    main_formula, pkt_range = get_main_formula(config)
  File "/home/tldart/gauntlet/bin/../src/generate_p4_test.py", line 445, in get_main_formula
    pipes, result = get_prog_semantics(config)
  File "/home/tldart/gauntlet/bin/../src/generate_p4_test.py", line 141, in get_prog_semantics
    util.copy_file([p4_input, py_file], fail_dir)
  File "/home/tldart/gauntlet/src/util.py", line 40, in copy_file
    shutil.copy2(src_file, dst)
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tldart/gauntlet/validated/out/out.py'
```

**Comment by fruffy** [comment]
Unfortunately, `generate_test_case` has never been updated to use the C++ version. 

https://github.com/p4gauntlet/gauntlet/tree/gauntlet_old can you try on this branch and check whether it works there?

**Comment by TLDart** [comment]
Hi, sorry for the late response. I ended up not needing to use the generate_test_case utility and therefore have not tried using the old branch. Nevertheless, thanks for the response.
